// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: extensions.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Extension support defined in extensions.proto.

// MARK: - Extension Properties

// Swift Extensions on the exteneded Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_EnumValueOptions {

  var intValue: Int32 {
    get {return getExtensionValue(ext: Extensions_int_value) ?? 0}
    set {setExtensionValue(ext: Extensions_int_value, value: newValue)}
  }
  /// Returns true if extension `Extensions_int_value`
  /// has been explicitly set.
  var hasIntValue: Bool {
    return hasExtensionValue(ext: Extensions_int_value)
  }
  /// Clears the value of extension `Extensions_int_value`.
  /// Subsequent reads from it will return its default value.
  mutating func clearIntValue() {
    clearExtensionValue(ext: Extensions_int_value)
  }
}

extension SwiftProtobuf.Google_Protobuf_MessageOptions {

  var typeID: Int32 {
    get {return getExtensionValue(ext: Extensions_type_id) ?? 0}
    set {setExtensionValue(ext: Extensions_type_id, value: newValue)}
  }
  /// Returns true if extension `Extensions_type_id`
  /// has been explicitly set.
  var hasTypeID: Bool {
    return hasExtensionValue(ext: Extensions_type_id)
  }
  /// Clears the value of extension `Extensions_type_id`.
  /// Subsequent reads from it will return its default value.
  mutating func clearTypeID() {
    clearExtensionValue(ext: Extensions_type_id)
  }

}

// MARK: - File's ExtensionMap: Extensions_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
let Extensions_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Extensions_type_id,
  Extensions_int_value
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

let Extensions_type_id = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufInt32>, SwiftProtobuf.Google_Protobuf_MessageOptions>(
  _protobuf_fieldNumber: 50001,
  fieldName: "type_id"
)

let Extensions_int_value = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufInt32>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 50002,
  fieldName: "int_value"
)
